name: Trigger Deployment Workflow

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      test_tag:
        description: 'Tag to test'
        required: true
        default: '0.0.0'

jobs:
  triggerRemoteWorkflow:
    runs-on: ubuntu-latest

    steps:
      - name: Set TAG environment variable
        run: echo "TAG=${{ github.event.inputs.test_tag || github.event.release.tag_name }}" >> $GITHUB_ENV
      - name: Trigger remote workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: optimizely
          repo: csharp-sdk-codesign
          ref: master
          github_token: ${{ secrets.GITHUB_TOKEN}
          workflow_file_name: publish.yml
          client_payload: '{"tag": "${{ env.TAG }}"}'
