name: Trigger Publish

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      test_tag:
        description: 'Tag to test'
        required: true
        default: '0.0.0'

jobs:
  triggerRemoteWorkflow:
    runs-on: ubuntu-latest

    steps:
      - name: Set TAG environment variable from workflow_dispatch
        if: github.event_name == 'workflow_dispatch' # Check if workflow was manually triggered
        run: echo "TAG=${{ github.event.inputs.test_tag }}" >> $GITHUB_ENV
      - name: Set TAG environment variable from release tag
        if: github.event_name == 'release' # Check if workflow was triggered by a release event
        run: echo "TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV
      - name: Trigger remote workflow
        uses: convictional/trigger-workflow-and-wait@v1.6.1
        with:
          owner: optimizely
          repo: csharp-sdk-codesign
          ref: master
          github_token: ${{ secrets.GITHUB_TOKEN}
          workflow_file_name: publish.yml
          client_payload: '{"tag": "${{ env.TAG }}"}'
