name: Jira ticket reference check

on:
  pull_request:
     types: [opened, edited, reopened, synchronize]

jobs:
  jira_ticket_reference_check:
    name: Jira Ticket Reference Check
    runs-on: ubuntu-latest
    steps:
      - name: Check for Jira ticket reference
        uses: optimizely/github-action-ticket-reference-checker-public@master
        with:
          bodyRegex: 'FSSDK-(?<ticketNumber>\d+)' 
